# Generated by Django 5.0.3 on 2024-07-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0002_restaurant_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_images/"),
        ),
    ]
