# Generated by Django 5.0.3 on 2024-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0003_food_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="nutrition_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="restaurant_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
