# Generated by Django 5.0.3 on 2024-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_alter_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
